spring.application.name=backend
server.port=8080

# Supabase Database configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.fyuoewrpkebvtvkdmxsw
spring.datasource.password=Rms@postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable H2 console
spring.h2.console.enabled=false

# Hibernate auto table creation
spring.jpa.hibernate.ddl-auto=update

# Show SQL logs
spring.jpa.show-sql=true